version: "3.9"
services:
  server:
    build:
      context: .
      target: server
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080"
      timeout: 5s
      interval: 10s
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: .
      target: web
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000"
      timeout: 5s
      interval: 10s
    ports:
      - 3000:3000
    restart: unless-stopped
